<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataquality"
    nsURI="http://dataquality" nsPrefix="dataquality">
  <eSubpackages name="analysis" nsURI="http://dataquality.analysis" nsPrefix="dataquality.analysis">
    <eClassifiers xsi:type="ecore:EClass" name="Analysis" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwmx/analysis/informationreporting/ReportGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//analysis/AnalysisContext"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="results" eType="#//analysis/AnalysisResult"
          containment="true" eOpposite="#//analysis/AnalysisResult/analysis"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//analysis/AnalysisParameters"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnalysisContext" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwmx/analysis/informationreporting/ReportGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connection" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/foundation/softwaredeployment/DataManager"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="analysedElements" upperBound="-1"
          eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/ModelElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="the analysed object (could be a Catalog, a Schema, a Table, a ColumnSet, a Column, ...)"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnalysisParameters" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwmx/analysis/informationreporting/ReportGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFilter" upperBound="-1"
          eType="#//domain/Domain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Data filtered from the analysis. Data outside this domain are not taken into account for the analysis."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="indicatorValidationDomains"
          upperBound="-1" eType="#//domain/Domain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="@deprecated (is now on indicator) &#xA;FIXME scorreia remove this method in model.&#xA;Thresholds (or patterns) on indicators. Indicator that do not respect these thresholds are used to compute a quality indicator."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataValidationDomains"
          upperBound="-1" eType="#//domain/Domain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="@deprecated (is now on indicator) &#xA;FIXME scorreia remove this method in model.&#xA;The domain that defines the valid data. It can be patterns or thresholds, or more complex validation function. &#xA;This is not a filter. Data that do not respect these domain are counted in the analysis but are used to compute a quality indicator."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysisType" eType="#//analysis/AnalysisType"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="deactivatedIndicators"
          upperBound="-1" eType="#//indicators/Indicator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Gives a list of indicators that must not be evaluated. This is mainly useful in Comparison analyses when two indicators are always created but only one needs to be computed sometimes. "/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnalysisResult" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwmx/analysis/informationreporting/ReportGroup">
      <eStructuralFeatures xsi:type="ecore:EReference" name="analysis" eType="#//analysis/Analysis"
          eOpposite="#//analysis/Analysis/results"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultMetadata" eType="#//analysis/ExecutionInformations"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="indicatorValues" upperBound="-1"
          eType="#//domain/LiteralValue" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="TODO scorreia remove?&#xA;@deprecated will be removed from the model."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="indicators" upperBound="-1"
          eType="#//indicators/Indicator" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionInformations">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A number which is incremented each time the analysis is executed. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastRunOk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Tells whether the last run is ok."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastExecutionNumberOk"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Stores the number of the last execution which has run correctly."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="AnalysisType">
      <eLiterals name="COLUMN" literal="Column Analysis"/>
      <eLiterals name="COLUMNS_COMPARISON" value="1" literal="Columns Comparison Analysis"/>
      <eLiterals name="TABLE" value="2" literal="Table Analysis"/>
      <eLiterals name="TABLE_COMPARISON" value="3" literal="Table Comparison"/>
      <eLiterals name="CONNECTION" value="4" literal="Connection Analysis"/>
      <eLiterals name="SCHEMA" value="5" literal="Schema Analysis"/>
      <eLiterals name="MULTIPLE_COLUMN" value="6" literal="Multiple Column Analysis"/>
      <eLiterals name="CATALOG" value="7" literal="Catalog Analysis"/>
      <eLiterals name="COLUMN_CORRELATION" value="8" literal="Column Correlation Analysis"/>
    </eClassifiers>
    <eSubpackages name="category" nsURI="http://org.talend.dataquality.category" nsPrefix="dataquality.category">
      <eClassifiers xsi:type="ecore:EClass" name="AnalysisCategory">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysisType" eType="#//analysis/AnalysisType"
            defaultValueLiteral="" unsettable="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="subCategories" upperBound="-1"
            eType="#//analysis/category/AnalysisCategory" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AnalysisCategories">
        <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
            eType="#//analysis/category/AnalysisCategory" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="reports" nsURI="http://dataquality.reports" nsPrefix="dataquality.reports">
    <eClassifiers xsi:type="ecore:EClass" name="TdReport" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwmx/analysis/informationreporting/Report">
      <eOperations name="addAnalysis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="analysis" eType="#//analysis/Analysis"/>
      </eOperations>
      <eOperations name="removeAnalysis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="analysis" eType="#//analysis/Analysis"/>
      </eOperations>
      <eOperations name="setMustRefresh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="analysis" eType="#//analysis/Analysis"/>
        <eParameters name="mustRefresh" eType="ecore:EDataType ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Boolean"/>
      </eOperations>
      <eOperations name="addAnalysis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="analysis" eType="#//analysis/Analysis"/>
        <eParameters name="mustRefresh" eType="ecore:EDataType ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Boolean"/>
      </eOperations>
      <eOperations name="mustRefresh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="analysis" eType="#//analysis/Analysis"/>
      </eOperations>
      <eOperations name="setReportPresentationParam" eType="#//reports/PresentationParameter">
        <eParameters name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="formula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="presentationParams" upperBound="-1"
          eType="#//reports/PresentationParameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="analysisMap" upperBound="-1"
          eType="#//reports/AnalysisMap" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputJrxml" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The input jasper report xml file."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputReportFolder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The folder where the reports generated by jasper will be archived."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reportType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The type of report. Types of report can be &quot;snapshot&quot; or &quot;temporal&quot; for the moment. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ExecInformations" eType="#//analysis/ExecutionInformations"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PresentationParameter" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/analysis/informationvisualization/Rendering">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="plotType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A string indicating the type of the plot that is used to display the indicator."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="indicator" eType="#//indicators/Indicator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AnalysisMap">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This class maps the analysis to the &quot;refresh&quot; boolean. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="analysis" eType="#//analysis/Analysis"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mustRefresh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="True when the analysis must be recomputed each time the report is run. "/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="indicators" nsURI="http://dataquality.indicators" nsPrefix="dataquality.indicators">
    <eClassifiers xsi:type="ecore:EClass" name="Indicator" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/ModelElement">
      <eOperations name="handle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="reset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getPurpose" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getLongDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="prepare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Prepares this indicator for a computation. This method can be used for initialization some internal state data from parameters. Or initializing some internal values before handling data. "/>
        </eAnnotations>
      </eOperations>
      <eOperations name="finalizeComputation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="can be called after having given all objects to handle. Subclasses can use this method for doing some computation that must be done at the end only."/>
        </eAnnotations>
      </eOperations>
      <eOperations name="storeSqlResults" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Stores the results of an SQL query."/>
        </eAnnotations>
        <eParameters name="objects" eType="#//indicators/ObjectArray"/>
      </eOperations>
      <eOperations name="getInstantiatedExpressions" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Returns the instantiated expression for the given language or null."/>
        </eAnnotations>
        <eParameters name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="setInstantiatedExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Sets the expression in the list of instantiated expressions. If an expression for the given language already exists, it is updated. Otherwise the expression is added to the list."/>
        </eAnnotations>
        <eParameters name="expression" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Expression"/>
      </eOperations>
      <eOperations name="getIntegerValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eOperations name="getRealValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
      <eOperations name="getValueType" eType="#//indicators/IndicatorValueType"/>
      <eOperations name="getInstanceValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Return the instance value of the indicator or null when not applicable."/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//indicators/IndicatorParameters"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedElement" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/ModelElement"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataminingType" eType="#//indicators/DataminingType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="indicatorDefinition"
          eType="#//indicators/definition/IndicatorDefinition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiatedExpressions"
          upperBound="-1" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Expression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RowCountIndicator" eSuperTypes="#//indicators/Indicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="MeanIndicator" eSuperTypes="#//indicators/SumIndicator">
      <eOperations name="getMean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
      <eOperations name="getMeanWithNulls" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Return the mean by taking into account the null values replaced by the given parameter (usually 0). "/>
        </eAnnotations>
        <eParameters name="valueForNull" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SumIndicator" eSuperTypes="#//indicators/Indicator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sumStr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Java data type of the summed data"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeIndicator" eSuperTypes="#//indicators/Indicator">
      <eOperations name="getChildIndicators" upperBound="-1" eType="#//indicators/Indicator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Returns the direct children of this composite indicator."/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getLeafIndicators" upperBound="-1" eType="#//indicators/Indicator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Returns the indicators that are leaf of the tree."/>
        </eAnnotations>
      </eOperations>
      <eOperations name="getAllChildIndicators" upperBound="-1" eType="#//indicators/Indicator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Returns all the child indicators (leaf indicators or intermediate composite indicators) as a flat list."/>
        </eAnnotations>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RangeIndicator" eSuperTypes="#//indicators/CompositeIndicator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lowerValue" eType="#//indicators/MinValueIndicator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upperValue" eType="#//indicators/MaxValueIndicator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="range" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BoxIndicator" eSuperTypes="#//indicators/CompositeIndicator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="IQR" eType="#//indicators/IQRIndicator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rangeIndicator" eType="#//indicators/RangeIndicator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="meanIndicator" eType="#//indicators/MeanIndicator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="medianIndicator" eType="#//indicators/MedianIndicator"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FrequencyIndicator" eSuperTypes="#//indicators/Indicator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Stores Frequencies for each value.&#xA;TODO store them in EMF (need to be modeled). "/>
      </eAnnotations>
      <eOperations name="getCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="returns the number of apparition of the given data."/>
        </eAnnotations>
        <eParameters name="dataValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="getFrequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="returns the frequency (between 0 and 1)"/>
        </eAnnotations>
        <eParameters name="dataValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="getDistinctValues" eType="#//indicators/JavaSet"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueValues" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="distinctValueCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueValueCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duplicateValueCount"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          changeable="false" volatile="true" transient="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueToFreq" eType="#//indicators/JavaHashMap"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlankCountIndicator" eSuperTypes="#//indicators/Indicator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blankCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndicatorParameters">
      <eStructuralFeatures xsi:type="ecore:EReference" name="indicatorValidDomain"
          eType="#//domain/Domain" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Thresholds (or patterns) on indicators. Indicator that do not respect these thresholds are used to compute a quality indicator."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataValidDomain" eType="#//domain/Domain"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The domain that defines the valid data. It can be patterns or thresholds, or more complex validation function. &#xA;This is not a filter. Data that do not respect these domain are counted in the analysis but are used to compute a quality indicator."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bins" eType="#//domain/Domain"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The bins definition (if any). Bins' definition is usually used for aggregating data into bins. "/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="textParameter" eType="#//indicators/TextParameters"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dateParameters" eType="#//indicators/DateParameters"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="topN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="10">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The number of values used in frequency tables"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MedianIndicator" eSuperTypes="#//indicators/Indicator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="TODO model the frequency table"/>
      </eAnnotations>
      <eOperations name="computeMedian" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="computes the median and update attribute &quot;median&quot;."/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="median" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
          unsettable="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The median value"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequenceTable" eType="#//indicators/JavaTreeMap"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateMedian" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="When computing median on date columns, this method returns the median as a date. The method this.getMedian() returns the date as a numeric value instead."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="JavaSet" instanceClassName="java.util.Set&lt;Object>"/>
    <eClassifiers xsi:type="ecore:EDataType" name="JavaHashMap" instanceClassName="java.util.HashMap&lt;Object, java.lang.Long>"/>
    <eClassifiers xsi:type="ecore:EDataType" name="JavaTreeMap" instanceClassName="java.util.TreeMap&lt;Object, java.lang.Long>"/>
    <eClassifiers xsi:type="ecore:EEnum" name="EnumStatistics">
      <eLiterals name="MIN_VALUE" literal="Minimal value"/>
      <eLiterals name="MAX_VALUE" value="1" literal="Maximal value"/>
      <eLiterals name="LOWER_QUARTILE" value="2" literal="Lower quartile"/>
      <eLiterals name="UPPER_QUARTILE" value="3" literal="Upper quartile"/>
      <eLiterals name="MEAN" value="4" literal="Mean"/>
      <eLiterals name="MEDIAN" value="5" literal="Median"/>
      <eLiterals name="ROW_COUNT" literal="Row count"/>
      <eLiterals name="NULL_COUNT" value="1" literal="Null count"/>
      <eLiterals name="DISTINCT_COUNT" value="2" literal="Distinct count"/>
      <eLiterals name="UNIQUE_COUNT" value="3" literal="Unique count"/>
      <eLiterals name="DUPLICATE_COUNT" value="4" literal="Duplicate count"/>
      <eLiterals name="BOX"/>
      <eLiterals name="FREQ_TABLE" value="1" literal="Frequency table"/>
      <eLiterals name="RANGE" value="2" literal="Range"/>
      <eLiterals name="IQR" value="3" literal="Inter quartile range"/>
      <eLiterals name="BIN_COUNT" value="4" literal="Bin count"/>
      <eLiterals name="MATCHING_VALUES" literal="Matching values"/>
      <eLiterals name="BLANK_COUNT" literal="Blank count"/>
      <eLiterals name="MIN_LENGTH" value="1" literal="Minimal length"/>
      <eLiterals name="MAX_LENGTH" value="2" literal="Maximal length"/>
      <eLiterals name="AVG_LENGTH" value="3" literal="Average length"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DataminingType">
      <eLiterals name="NOMINAL" literal="Nominal"/>
      <eLiterals name="INTERVAL" value="1" literal="Interval"/>
      <eLiterals name="UNSTRUCTURED_TEXT" value="2" literal="Unstructured Text">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Used for long text"/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="OTHER" value="3" literal="Other">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Could be binary data, geometrical data..."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueIndicator" eSuperTypes="#//indicators/Indicator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="datatype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MinValueIndicator" eSuperTypes="#//indicators/ValueIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="MaxValueIndicator" eSuperTypes="#//indicators/ValueIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="ModeIndicator" eSuperTypes="#//indicators/Indicator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="most frequent value"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NullCountIndicator" eSuperTypes="#//indicators/Indicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="DistinctCountIndicator" eSuperTypes="#//indicators/Indicator">
      <eOperations name="getDistinctValues" eType="#//indicators/JavaSet">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Returns the set of distinct values. (This set is larger than the Unique values set)."/>
        </eAnnotations>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="distinctValueCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UniqueCountIndicator" eSuperTypes="#//indicators/Indicator">
      <eOperations name="getUniqueValues" eType="#//indicators/JavaSet"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueValueCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DuplicateCountIndicator" eSuperTypes="#//indicators/Indicator">
      <eOperations name="getDuplicateValues" eType="#//indicators/JavaSet"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="duplicateValueCount"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IQRIndicator" eSuperTypes="#//indicators/RangeIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="TextIndicator" eSuperTypes="#//indicators/CompositeIndicator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="averageLengthIndicator"
          eType="#//indicators/AverageLengthIndicator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="maxLengthIndicator" eType="#//indicators/MaxLengthIndicator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="MinLengthIndicator" eType="#//indicators/MinLengthIndicator"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MinLengthIndicator" eSuperTypes="#//indicators/LengthIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="MaxLengthIndicator" eSuperTypes="#//indicators/LengthIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="AverageLengthIndicator" eSuperTypes="#//indicators/LengthIndicator">
      <eOperations name="getAverageLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sumLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LengthIndicator" eSuperTypes="#//indicators/Indicator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DateGrain">
      <eLiterals name="DAY" value="6" literal="day"/>
      <eLiterals name="WEEK" value="1" literal="week"/>
      <eLiterals name="MONTH" value="2" literal="month"/>
      <eLiterals name="QUARTER" value="3" literal="quarter"/>
      <eLiterals name="YEAR" value="5" literal="year"/>
      <eLiterals name="NONE" literal="none"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextParameters">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="useBlank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchingAlgorithm" eType="#//indicators/MatchingAlgorithm"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreCase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="useNulls" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="MatchingAlgorithm">
      <eLiterals name="EXACT" literal="Exact match"/>
      <eLiterals name="METAPHONE" value="1" literal="Metaphone"/>
      <eLiterals name="DOUBLE_METAPHONE" value="2" literal="Double metaphone"/>
      <eLiterals name="LEVENSHTEIN" value="3" literal="Levenshtein"/>
      <eLiterals name="SOUNDEX" value="4" literal="Soundex"/>
      <eLiterals name="REFINED_SOUNDEX" value="5" literal="Refined Soundex"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="ObjectArray" instanceClassName="java.util.List&lt;Object[]>"/>
    <eClassifiers xsi:type="ecore:EClass" name="LowerQuartileIndicator" eSuperTypes="#//indicators/MinValueIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="UpperQuartileIndicator" eSuperTypes="#//indicators/MaxValueIndicator"/>
    <eClassifiers xsi:type="ecore:EEnum" name="IndicatorValueType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The indicator content values (useful for historization of indicator in the TALEND_DQ data mart)."/>
      </eAnnotations>
      <eLiterals name="INTEGER_VALUE" literal="I">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Tells that the indicator contains integer values (for example, row count, distinct count, text length...)"/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="REAL_VALUE" value="1" literal="R">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Tells that the indicator contains real values (for example when computing a mean on float data)"/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="INSTANCE_VALUE" value="2" literal="V">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This type of value is for indicators when the content of the indicator is an instance of the data (For example for the ModeIndicator). "/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CountsIndicator" eSuperTypes="#//indicators/CompositeIndicator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="blankCountIndicator"
          eType="#//indicators/BlankCountIndicator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="RowCountIndicator" eType="#//indicators/RowCountIndicator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="NullCountIndicator" eType="#//indicators/NullCountIndicator"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="UniqueCountIndicator"
          eType="#//indicators/UniqueCountIndicator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distinctCountIndicator"
          eType="#//indicators/DistinctCountIndicator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="duplicateCountIndicator"
          eType="#//indicators/DuplicateCountIndicator" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateParameters">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateAggregationType"
          eType="#//indicators/DateGrain" defaultValueLiteral="year"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PatternMatchingIndicator" abstract="true"
        eSuperTypes="#//indicators/MatchingIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="SqlPatternMatchingIndicator" eSuperTypes="#//indicators/PatternMatchingIndicator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This indicator handles &quot;SQL patterns&quot;. These patterns are expressions that can be placed in like clauses."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RegexpMatchingIndicator" eSuperTypes="#//indicators/PatternMatchingIndicator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This indicator handles regular expressions. These expressions need the database support of regular expressions."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchingIndicator" abstract="true"
        eSuperTypes="#//indicators/Indicator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="matchingValueCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="notMatchingValueCount"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LowFrequencyIndicator" eSuperTypes="#//indicators/FrequencyIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="PatternFreqIndicator" eSuperTypes="#//indicators/FrequencyIndicator"/>
    <eClassifiers xsi:type="ecore:EClass" name="PatternLowFreqIndicator" eSuperTypes="#//indicators/LowFrequencyIndicator"/>
    <eSubpackages name="schema" nsURI="http://dataquality.indicators.schema" nsPrefix="dataquality.indicators.schema">
      <eClassifiers xsi:type="ecore:EClass" name="SchemaIndicator" eSuperTypes="#//indicators/CompositeIndicator">
        <eOperations name="addTableIndicator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="tableIndicator" eType="#//indicators/schema/TableIndicator"/>
        </eOperations>
        <eOperations name="addViewIndicator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="viewIndicator" eType="#//indicators/schema/ViewIndicator"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggerCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableRowCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The number of rows of the analyzed tables."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tableIndicators" upperBound="-1"
            eType="#//indicators/schema/TableIndicator" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewRowCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The number of rows of the analyzed views."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="viewIndicators" upperBound="-1"
            eType="#//indicators/schema/ViewIndicator" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TableIndicator" eSuperTypes="#//indicators/schema/AbstractTableIndicator">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Number of Primary keys"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Number of indices"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConnectionIndicator" eSuperTypes="#//indicators/schema/CatalogIndicator">
        <eOperations name="addCatalogIndicator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="catalogIndicator" eType="#//indicators/schema/CatalogIndicator"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="catalogIndicators"
            upperBound="-1" eType="#//indicators/schema/CatalogIndicator" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="catalogCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CatalogIndicator" eSuperTypes="#//indicators/schema/SchemaIndicator">
        <eOperations name="addSchemaIndicator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
          <eParameters name="schemaIndicator" eType="#//indicators/schema/SchemaIndicator"/>
        </eOperations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="schemaCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="schemaIndicators" upperBound="-1"
            eType="#//indicators/schema/SchemaIndicator" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ViewIndicator" eSuperTypes="#//indicators/schema/AbstractTableIndicator"/>
      <eClassifiers xsi:type="ecore:EClass" name="AbstractTableIndicator" eSuperTypes="#//indicators/Indicator">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Number of rows of the analyzed element (Table, View...)"/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="definition" nsURI="http://dataquality.indicators.definition"
        nsPrefix="dataquality.indicators.definition">
      <eClassifiers xsi:type="ecore:EClass" name="IndicatorsDefinitions" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/ModelElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="indicatorDefinitions"
            upperBound="-1" eType="#//indicators/definition/IndicatorDefinition" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
            eType="#//indicators/definition/IndicatorCategory" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IndicatorDefinition" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/ModelElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
            eType="#//indicators/definition/IndicatorCategory"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="aggregatedDefinitions"
            upperBound="-1" eType="#//indicators/definition/IndicatorDefinition"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            iD="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="subCategories" upperBound="-1"
            eType="#//indicators/definition/IndicatorCategory"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="sqlGenericExpression"
            upperBound="-1" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeric1argFunctions"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="list of numeric functions to be used by this indicator definition (e.g. AVG({0)}, SUM({0}), COUNT({0})...)&#xA;"/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IndicatorCategory" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/ModelElement">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            iD="true"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="sql" nsURI="http://dataquality.indicators.sql" nsPrefix="dataquality.indicators.sql">
      <eClassifiers xsi:type="ecore:EClass" name="SqlIndicator" eSuperTypes="#//indicators/Indicator">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModificationDate"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="columnset" nsURI="http://dataquality.indicators.columnset"
        nsPrefix="dataquality.indicators.columnset">
      <eClassifiers xsi:type="ecore:EClass" name="ColumnsCompareIndicator" abstract="true"
          eSuperTypes="#//indicators/MatchingIndicator">
        <eStructuralFeatures xsi:type="ecore:EReference" name="columnSetA" upperBound="-1"
            eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/resource/relational/Column"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="columnSetB" upperBound="-1"
            eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/resource/relational/Column"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ValueMatchingIndicator" eSuperTypes="#//indicators/columnset/ColumnsCompareIndicator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="counts the number of value matching or not matching when comparing two or more columns"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RowMatchingIndicator" eSuperTypes="#//indicators/columnset/ColumnsCompareIndicator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="counts the number of rows matching or not matching when comparing two or more columns"/>
        </eAnnotations>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ColumnSetMultiValueIndicator" eSuperTypes="#//indicators/Indicator">
        <eStructuralFeatures xsi:type="ecore:EReference" name="analyzedColumns" upperBound="-1"
            eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/resource/relational/Column"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="listRows" eType="#//indicators/ObjectArray"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="numericFunctions" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="nominalColumns" upperBound="-1"
            eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/resource/relational/Column"
            changeable="false" volatile="true" transient="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="numericColumns" upperBound="-1"
            eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/resource/relational/Column"
            changeable="false" volatile="true" transient="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CountAvgNullIndicator" eSuperTypes="#//indicators/columnset/ColumnSetMultiValueIndicator"/>
      <eClassifiers xsi:type="ecore:EDataType" name="ListObject" instanceClassName="java.util.List&lt;Object>"/>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="http://dataquality.expressions" nsPrefix="dataquality.expressions">
    <eClassifiers xsi:type="ecore:EClass" name="BooleanExpressionNode" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/foundation/expressions/ExpressionNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="See http://portal.acm.org/citation.cfm?id=1274453.1274459"/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="domain" nsURI="http://dataquality.domain" nsPrefix="dataquality.domain">
    <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Namespace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/DataType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lengthRestriction" upperBound="-1"
          eType="#//domain/LengthRestriction" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ranges" upperBound="-1"
          eType="#//domain/RangeRestriction" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
          eType="#//domain/pattern/Pattern"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationRule">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Association class."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domain" upperBound="-1"
          eType="#//domain/Domain"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/foundation/datatypes/Enumeration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RangeRestriction" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="lowerValue" eType="#//domain/LiteralValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="upperValue" eType="#//domain/LiteralValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" eType="#//expressions/BooleanExpressionNode"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="encodeValueMeaning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LengthRestriction">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumericValue" eSuperTypes="#//domain/LiteralValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="TextValue" eSuperTypes="#//domain/LiteralValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerValue" eSuperTypes="#//domain/NumericValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RealNumberValue" eSuperTypes="#//domain/NumericValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateValue" eSuperTypes="#//domain/NumericValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    </eClassifiers>
    <eSubpackages name="pattern" nsURI="http://dataquality.domain.pattern" nsPrefix="dataquality.domain.pattern">
      <eClassifiers xsi:type="ecore:EClass" name="Pattern" eSuperTypes="../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/ModelElement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
            eType="#//domain/pattern/PatternComponent" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PatternComponent"/>
      <eClassifiers xsi:type="ecore:EClass" name="RegularExpression" eSuperTypes="#//domain/pattern/PatternComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Expression"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The type of regular expression: can be either &quot;regexp&quot; or &quot;sql like&quot; to differentiate between the regular patterns and the SQL expressions available for the LIKE clause."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AttributeReference" eSuperTypes="#//domain/pattern/PatternComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="referencedAttribute"
            eType="ecore:EClass ../../org.talend.cwm.mip/model/CWM.ecore#//cwm/objectmodel/core/Attribute"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ComponentReference" eSuperTypes="#//domain/pattern/PatternComponent">
        <eStructuralFeatures xsi:type="ecore:EReference" name="referencedComponent"
            eType="#//domain/pattern/PatternComponent"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="ExpressionType">
        <eLiterals name="REGEXP"/>
        <eLiterals name="SQL_LIKE" value="1" literal="SQL like"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="sql" nsURI="http://dataquality.domain.sql" nsPrefix="dataquality.domain.sql">
      <eClassifiers xsi:type="ecore:EEnum" name="SqlPredicate">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="See http://www.experlog.com/gibello/zql/sqltut.html#Relational%20Operators"/>
        </eAnnotations>
        <eLiterals name="EQUAL" literal="="/>
        <eLiterals name="NOT_EQUAL" value="1" literal="&lt;>">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Some DBMS do not support the != not equal syntax. In this case, use this syntax."/>
          </eAnnotations>
        </eLiterals>
        <eLiterals name="GREATER" value="2" literal=">"/>
        <eLiterals name="LESS" value="3" literal="&lt;"/>
        <eLiterals name="GREATER_EQUAL" value="4" literal=">="/>
        <eLiterals name="LESS_EQUAL" value="5" literal="&lt;="/>
        <eLiterals name="IS_NULL" value="6" literal="IS NULL"/>
        <eLiterals name="BETWEEN" value="7"/>
        <eLiterals name="LIKE" value="8"/>
        <eLiterals name="IN" value="9"/>
        <eLiterals name="NOT_EQUAL2" value="10" literal="!=">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Some DBMS do not support the &lt;> not equal syntax. In this case, use this syntax."/>
          </eAnnotations>
        </eLiterals>
        <eLiterals name="NOT_IN" value="11" literal="NOT IN"/>
        <eLiterals name="NOT_BETWEEN" value="12" literal="NOT BETWEEN"/>
        <eLiterals name="NOT_LIKE" value="13" literal="NOT LIKE"/>
        <eLiterals name="IS_NOT_NULL" value="14" literal="IS NOT NULL"/>
        <eLiterals name="AND" value="15"/>
        <eLiterals name="OR" value="16"/>
        <eLiterals name="UNION" value="17"/>
        <eLiterals name="ALL" value="18"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="Bracket">
        <eLiterals name="LEFT" literal="("/>
        <eLiterals name="RIGHT" value="1" literal=")"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
