/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package orgomg.cwmx.analysis.informationset.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import orgomg.cwmx.analysis.informationset.util.InformationsetAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class InformationsetItemProviderAdapterFactory extends InformationsetAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object>();

    /**
     * This constructs an instance.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public InformationsetItemProviderAdapterFactory() {
        supportedTypes.add(IEditingDomainItemProvider.class);
        supportedTypes.add(IStructuredItemContentProvider.class);
        supportedTypes.add(ITreeItemContentProvider.class);
        supportedTypes.add(IItemLabelProvider.class);
        supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all {@link orgomg.cwmx.analysis.informationset.InformationSet} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InformationSetItemProvider informationSetItemProvider;

    /**
     * This creates an adapter for a {@link orgomg.cwmx.analysis.informationset.InformationSet}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createInformationSetAdapter() {
        if (informationSetItemProvider == null) {
            informationSetItemProvider = new InformationSetItemProvider(this);
        }

        return informationSetItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link orgomg.cwmx.analysis.informationset.Segment} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SegmentItemProvider segmentItemProvider;

    /**
     * This creates an adapter for a {@link orgomg.cwmx.analysis.informationset.Segment}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSegmentAdapter() {
        if (segmentItemProvider == null) {
            segmentItemProvider = new SegmentItemProvider(this);
        }

        return segmentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link orgomg.cwmx.analysis.informationset.SegmentRegion} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SegmentRegionItemProvider segmentRegionItemProvider;

    /**
     * This creates an adapter for a {@link orgomg.cwmx.analysis.informationset.SegmentRegion}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createSegmentRegionAdapter() {
        if (segmentRegionItemProvider == null) {
            segmentRegionItemProvider = new SegmentRegionItemProvider(this);
        }

        return segmentRegionItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link orgomg.cwmx.analysis.informationset.Rule} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected RuleItemProvider ruleItemProvider;

    /**
     * This creates an adapter for a {@link orgomg.cwmx.analysis.informationset.Rule}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createRuleAdapter() {
        if (ruleItemProvider == null) {
            ruleItemProvider = new RuleItemProvider(this);
        }

        return ruleItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link orgomg.cwmx.analysis.informationset.InfoSetAdministration} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InfoSetAdministrationItemProvider infoSetAdministrationItemProvider;

    /**
     * This creates an adapter for a {@link orgomg.cwmx.analysis.informationset.InfoSetAdministration}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createInfoSetAdministrationAdapter() {
        if (infoSetAdministrationItemProvider == null) {
            infoSetAdministrationItemProvider = new InfoSetAdministrationItemProvider(this);
        }

        return infoSetAdministrationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link orgomg.cwmx.analysis.informationset.InfoSetDate} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InfoSetDateItemProvider infoSetDateItemProvider;

    /**
     * This creates an adapter for a {@link orgomg.cwmx.analysis.informationset.InfoSetDate}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createInfoSetDateAdapter() {
        if (infoSetDateItemProvider == null) {
            infoSetDateItemProvider = new InfoSetDateItemProvider(this);
        }

        return infoSetDateItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public boolean isFactoryForType(Object type) {
        return supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter adapt(Notifier notifier, Object type) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Object adapt(Object object, Object type) {
        if (isFactoryForType(type)) {
            Object adapter = super.adapt(object, type);
            if (!(type instanceof Class) || (((Class<?>)type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void addListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void removeListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void fireNotifyChanged(Notification notification) {
        changeNotifier.fireNotifyChanged(notification);

        if (parentAdapterFactory != null) {
            parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

    /**
     * This disposes all of the item providers created by this factory. 
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void dispose() {
        if (informationSetItemProvider != null) informationSetItemProvider.dispose();
        if (segmentItemProvider != null) segmentItemProvider.dispose();
        if (segmentRegionItemProvider != null) segmentRegionItemProvider.dispose();
        if (ruleItemProvider != null) ruleItemProvider.dispose();
        if (infoSetAdministrationItemProvider != null) infoSetAdministrationItemProvider.dispose();
        if (infoSetDateItemProvider != null) infoSetDateItemProvider.dispose();
    }

}
